# TensorFlow 初心者向けクイックスタート
URL: https://www.tensorflow.org/tutorials/quickstart/beginner?hl=ja

In [16]:
import tensorflow as tf

In [17]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [18]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [19]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.39191997, -0.10780647,  0.7790062 ,  0.7907134 ,  0.26029602,
         0.478612  , -0.37954783,  0.71432394,  0.13495223,  0.25492802]],
      dtype=float32)

In [20]:
tf.nn.softmax(predictions).numpy()

array([[0.09975277, 0.06051967, 0.14690426, 0.14863421, 0.08745032,
        0.10878646, 0.04611909, 0.13770294, 0.07714812, 0.08698215]],
      dtype=float32)

In [21]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [22]:
loss_fn(y_train[:1], predictions).numpy()

2.2183683

In [23]:
model.compile(optimizer='adam',
             loss=loss_fn,
             metrics=['accuracy'])

In [24]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.4736 - accuracy: 0.8597
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1480 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1095 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0854 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0739 - accuracy: 0.9768


In [27]:
model.evaluate(x_test, y_test, verbose=1)

313/313 [==============================] - 1s 2ms/step - loss: 0.0749 - accuracy: 0.9770


[0.0749078318476677, 0.9769999980926514]

In [29]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [30]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.2526759e-09, 1.9311992e-09, 4.2827105e-07, 4.3045031e-04,
        4.7986107e-12, 6.7848420e-09, 4.7662578e-15, 9.9956125e-01,
        1.2542913e-06, 6.6338343e-06],
       [1.2121899e-07, 9.0720496e-05, 9.9990523e-01, 3.1291929e-06,
        5.8460499e-16, 3.0910277e-07, 8.6727070e-09, 8.0405280e-14,
        5.2379414e-07, 2.9889160e-14],
       [2.8684462e-07, 9.9817836e-01, 3.4192481e-04, 9.6298600e-06,
        3.3097484e-05, 2.9617338e-05, 1.1664634e-04, 1.0355865e-03,
        2.5429306e-04, 5.3965863e-07],
       [9.9996758e-01, 5.2915956e-09, 7.8726389e-06, 8.6343925e-07,
        1.2425801e-07, 1.4291758e-05, 4.9380043e-07, 4.8412089e-06,
        2.4327553e-08, 3.8908520e-06],
       [1.7038081e-05, 1.3471714e-09, 1.0422433e-05, 5.5359088e-08,
        9.9611652e-01, 1.0481476e-06, 3.3511264e-05, 9.4833056e-05,
        5.1072606e-05, 3.6755572e-03]], dtype=float32)>